"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.get = void 0;
const get = (url) => {
    console.log("Pozvao me: " + url);
    if (url.includes("singleMatch.php?country=")) {
        return Promise.resolve({
            main: [
                {
                    gameDate: "2022-04-18",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "IF Gnistan",
                    awayTeam: "PK-35 Vantaa",
                    winnerFT: "d",
                    winnerFH: "d",
                    winnerSH: "d",
                    result: "1 - 1",
                    homeScoreFirstHalf: 1,
                    awayScoreFirstHalf: 1,
                    homeScoreSecondHalf: 0,
                    awayScoreSecondHalf: 0,
                    homeScoreFullTime: 1,
                    awayScoreFullTime: 1,
                    goalsFT: 2,
                    goalsHT: 2,
                },
                {
                    gameDate: "2022-04-18",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "JäPS",
                    awayTeam: "FF Jaro",
                    winnerFT: "d",
                    winnerFH: "d",
                    winnerSH: "d",
                    result: "0 - 0",
                    homeScoreFirstHalf: 0,
                    awayScoreFirstHalf: 0,
                    homeScoreSecondHalf: 0,
                    awayScoreSecondHalf: 0,
                    homeScoreFullTime: 0,
                    awayScoreFullTime: 0,
                    goalsFT: 0,
                    goalsHT: 0,
                },
                {
                    gameDate: "2022-04-18",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "KPV Kokkola",
                    awayTeam: "MP Mikkeli",
                    winnerFT: "h",
                    winnerFH: "h",
                    winnerSH: "a",
                    result: "3 - 2",
                    homeScoreFirstHalf: 3,
                    awayScoreFirstHalf: 0,
                    homeScoreSecondHalf: 0,
                    awayScoreSecondHalf: 2,
                    homeScoreFullTime: 3,
                    awayScoreFullTime: 2,
                    goalsFT: 5,
                    goalsHT: 3,
                },
                {
                    gameDate: "2022-04-18",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "FC KTP",
                    awayTeam: "PEPO",
                    winnerFT: "h",
                    winnerFH: "h",
                    winnerSH: "d",
                    result: "1 - 0",
                    homeScoreFirstHalf: 1,
                    awayScoreFirstHalf: 0,
                    homeScoreSecondHalf: 0,
                    awayScoreSecondHalf: 0,
                    homeScoreFullTime: 1,
                    awayScoreFullTime: 0,
                    goalsFT: 1,
                    goalsHT: 1,
                },
                {
                    gameDate: "2022-04-18",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "PIF Parainen",
                    awayTeam: "SJK Akatemia",
                    winnerFT: "a",
                    winnerFH: "d",
                    winnerSH: "a",
                    result: "0 - 2",
                    homeScoreFirstHalf: 0,
                    awayScoreFirstHalf: 0,
                    homeScoreSecondHalf: 0,
                    awayScoreSecondHalf: 2,
                    homeScoreFullTime: 0,
                    awayScoreFullTime: 2,
                    goalsFT: 2,
                    goalsHT: 0,
                },
                {
                    gameDate: "2022-04-18",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "EIF Ekenas",
                    awayTeam: "TPS Turku",
                    winnerFT: "a",
                    winnerFH: "a",
                    winnerSH: "a",
                    result: "1 - 3",
                    homeScoreFirstHalf: 0,
                    awayScoreFirstHalf: 1,
                    homeScoreSecondHalf: 1,
                    awayScoreSecondHalf: 2,
                    homeScoreFullTime: 1,
                    awayScoreFullTime: 3,
                    goalsFT: 4,
                    goalsHT: 1,
                },
                {
                    gameDate: "2022-04-23",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "EIF Ekenas",
                    awayTeam: "PEPO",
                    winnerFT: "h",
                    winnerFH: "a",
                    winnerSH: "h",
                    result: "2 - 1",
                    homeScoreFirstHalf: 0,
                    awayScoreFirstHalf: 1,
                    homeScoreSecondHalf: 2,
                    awayScoreSecondHalf: 0,
                    homeScoreFullTime: 2,
                    awayScoreFullTime: 1,
                    goalsFT: 3,
                    goalsHT: 1,
                },
                {
                    gameDate: "2022-04-23",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "KPV Kokkola",
                    awayTeam: "IF Gnistan",
                    winnerFT: "a",
                    winnerFH: "a",
                    winnerSH: "d",
                    result: "0 - 2",
                    homeScoreFirstHalf: 0,
                    awayScoreFirstHalf: 2,
                    homeScoreSecondHalf: 0,
                    awayScoreSecondHalf: 0,
                    homeScoreFullTime: 0,
                    awayScoreFullTime: 2,
                    goalsFT: 2,
                    goalsHT: 2,
                },
                {
                    gameDate: "2022-04-23",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "TPS Turku",
                    awayTeam: "JäPS",
                    winnerFT: "h",
                    winnerFH: "h",
                    winnerSH: "h",
                    result: "3 - 0",
                    homeScoreFirstHalf: 1,
                    awayScoreFirstHalf: 0,
                    homeScoreSecondHalf: 2,
                    awayScoreSecondHalf: 0,
                    homeScoreFullTime: 3,
                    awayScoreFullTime: 0,
                    goalsFT: 3,
                    goalsHT: 1,
                },
                {
                    gameDate: "2022-04-25",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "PK-35 Vantaa",
                    awayTeam: "PIF Parainen",
                    winnerFT: "d",
                    winnerFH: "a",
                    winnerSH: "h",
                    result: "2 - 2",
                    homeScoreFirstHalf: 1,
                    awayScoreFirstHalf: 2,
                    homeScoreSecondHalf: 1,
                    awayScoreSecondHalf: 0,
                    homeScoreFullTime: 2,
                    awayScoreFullTime: 2,
                    goalsFT: 4,
                    goalsHT: 3,
                },
                {
                    gameDate: "2022-04-28",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "FC KTP",
                    awayTeam: "TPS Turku",
                    winnerFT: "d",
                    winnerFH: "d",
                    winnerSH: "d",
                    result: "0 - 0",
                    homeScoreFirstHalf: 0,
                    awayScoreFirstHalf: 0,
                    homeScoreSecondHalf: 0,
                    awayScoreSecondHalf: 0,
                    homeScoreFullTime: 0,
                    awayScoreFullTime: 0,
                    goalsFT: 0,
                    goalsHT: 0,
                },
                {
                    gameDate: "2022-04-29",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "JäPS",
                    awayTeam: "KPV Kokkola",
                    winnerFT: "d",
                    winnerFH: "d",
                    winnerSH: "d",
                    result: "0 - 0",
                    homeScoreFirstHalf: 0,
                    awayScoreFirstHalf: 0,
                    homeScoreSecondHalf: 0,
                    awayScoreSecondHalf: 0,
                    homeScoreFullTime: 0,
                    awayScoreFullTime: 0,
                    goalsFT: 0,
                    goalsHT: 0,
                },
                {
                    gameDate: "2022-04-29",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "PEPO",
                    awayTeam: "FF Jaro",
                    winnerFT: "a",
                    winnerFH: "a",
                    winnerSH: "a",
                    result: "0 - 3",
                    homeScoreFirstHalf: 0,
                    awayScoreFirstHalf: 1,
                    homeScoreSecondHalf: 0,
                    awayScoreSecondHalf: 2,
                    homeScoreFullTime: 0,
                    awayScoreFullTime: 3,
                    goalsFT: 3,
                    goalsHT: 1,
                },
                {
                    gameDate: "2022-04-30",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "IF Gnistan",
                    awayTeam: "EIF Ekenas",
                    winnerFT: "d",
                    winnerFH: "d",
                    winnerSH: "d",
                    result: "1 - 1",
                    homeScoreFirstHalf: 0,
                    awayScoreFirstHalf: 0,
                    homeScoreSecondHalf: 1,
                    awayScoreSecondHalf: 1,
                    homeScoreFullTime: 1,
                    awayScoreFullTime: 1,
                    goalsFT: 2,
                    goalsHT: 0,
                },
                {
                    gameDate: "2022-04-30",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "PIF Parainen",
                    awayTeam: "MP Mikkeli",
                    winnerFT: "a",
                    winnerFH: "d",
                    winnerSH: "a",
                    result: "2 - 3",
                    homeScoreFirstHalf: 1,
                    awayScoreFirstHalf: 1,
                    homeScoreSecondHalf: 1,
                    awayScoreSecondHalf: 2,
                    homeScoreFullTime: 2,
                    awayScoreFullTime: 3,
                    goalsFT: 5,
                    goalsHT: 2,
                },
                {
                    gameDate: "2022-05-07",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "PK-35 Vantaa",
                    awayTeam: "PEPO",
                    winnerFT: "a",
                    winnerFH: "d",
                    winnerSH: "a",
                    result: "1 - 2",
                    homeScoreFirstHalf: 1,
                    awayScoreFirstHalf: 1,
                    homeScoreSecondHalf: 0,
                    awayScoreSecondHalf: 1,
                    homeScoreFullTime: 1,
                    awayScoreFullTime: 2,
                    goalsFT: 3,
                    goalsHT: 2,
                },
                {
                    gameDate: "2022-05-08",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "IF Gnistan",
                    awayTeam: "JäPS",
                    winnerFT: "h",
                    winnerFH: "h",
                    winnerSH: "h",
                    result: "10 - 1",
                    homeScoreFirstHalf: 5,
                    awayScoreFirstHalf: 1,
                    homeScoreSecondHalf: 5,
                    awayScoreSecondHalf: 0,
                    homeScoreFullTime: 10,
                    awayScoreFullTime: 1,
                    goalsFT: 11,
                    goalsHT: 6,
                },
                {
                    gameDate: "2022-05-08",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "MP Mikkeli",
                    awayTeam: "SJK Akatemia",
                    winnerFT: "d",
                    winnerFH: "d",
                    winnerSH: "d",
                    result: "1 - 1",
                    homeScoreFirstHalf: 1,
                    awayScoreFirstHalf: 1,
                    homeScoreSecondHalf: 0,
                    awayScoreSecondHalf: 0,
                    homeScoreFullTime: 1,
                    awayScoreFullTime: 1,
                    goalsFT: 2,
                    goalsHT: 2,
                },
                {
                    gameDate: "2022-05-08",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "KPV Kokkola",
                    awayTeam: "FC KTP",
                    winnerFT: "a",
                    winnerFH: "d",
                    winnerSH: "a",
                    result: "1 - 3",
                    homeScoreFirstHalf: 0,
                    awayScoreFirstHalf: 0,
                    homeScoreSecondHalf: 1,
                    awayScoreSecondHalf: 3,
                    homeScoreFullTime: 1,
                    awayScoreFullTime: 3,
                    goalsFT: 4,
                    goalsHT: 0,
                },
                {
                    gameDate: "2022-05-08",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "EIF Ekenas",
                    awayTeam: "FF Jaro",
                    winnerFT: "h",
                    winnerFH: "d",
                    winnerSH: "h",
                    result: "2 - 1",
                    homeScoreFirstHalf: 1,
                    awayScoreFirstHalf: 1,
                    homeScoreSecondHalf: 1,
                    awayScoreSecondHalf: 0,
                    homeScoreFullTime: 2,
                    awayScoreFullTime: 1,
                    goalsFT: 3,
                    goalsHT: 2,
                },
                {
                    gameDate: "2022-05-09",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "TPS Turku",
                    awayTeam: "PIF Parainen",
                    winnerFT: "a",
                    winnerFH: "d",
                    winnerSH: "a",
                    result: "0 - 2",
                    homeScoreFirstHalf: 0,
                    awayScoreFirstHalf: 0,
                    homeScoreSecondHalf: 0,
                    awayScoreSecondHalf: 2,
                    homeScoreFullTime: 0,
                    awayScoreFullTime: 2,
                    goalsFT: 2,
                    goalsHT: 0,
                },
                {
                    gameDate: "2022-05-11",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "SJK Akatemia",
                    awayTeam: "PK-35 Vantaa",
                    winnerFT: "h",
                    winnerFH: "h",
                    winnerSH: "h",
                    result: "4 - 1",
                    homeScoreFirstHalf: 2,
                    awayScoreFirstHalf: 1,
                    homeScoreSecondHalf: 2,
                    awayScoreSecondHalf: 0,
                    homeScoreFullTime: 4,
                    awayScoreFullTime: 1,
                    goalsFT: 5,
                    goalsHT: 3,
                },
                {
                    gameDate: "2022-05-13",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "JäPS",
                    awayTeam: "EIF Ekenas",
                    winnerFT: "h",
                    winnerFH: "h",
                    winnerSH: "d",
                    result: "1 - 0",
                    homeScoreFirstHalf: 1,
                    awayScoreFirstHalf: 0,
                    homeScoreSecondHalf: 0,
                    awayScoreSecondHalf: 0,
                    homeScoreFullTime: 1,
                    awayScoreFullTime: 0,
                    goalsFT: 1,
                    goalsHT: 1,
                },
                {
                    gameDate: "2022-05-14",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "PIF Parainen",
                    awayTeam: "KPV Kokkola",
                    winnerFT: "a",
                    winnerFH: "d",
                    winnerSH: "a",
                    result: "1 - 2",
                    homeScoreFirstHalf: 0,
                    awayScoreFirstHalf: 0,
                    homeScoreSecondHalf: 1,
                    awayScoreSecondHalf: 2,
                    homeScoreFullTime: 1,
                    awayScoreFullTime: 2,
                    goalsFT: 3,
                    goalsHT: 0,
                },
                {
                    gameDate: "2022-05-15",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "FF Jaro",
                    awayTeam: "PK-35 Vantaa",
                    winnerFT: "h",
                    winnerFH: "h",
                    winnerSH: "h",
                    result: "4 - 0",
                    homeScoreFirstHalf: 1,
                    awayScoreFirstHalf: 0,
                    homeScoreSecondHalf: 3,
                    awayScoreSecondHalf: 0,
                    homeScoreFullTime: 4,
                    awayScoreFullTime: 0,
                    goalsFT: 4,
                    goalsHT: 1,
                },
                {
                    gameDate: "2022-05-15",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "SJK Akatemia",
                    awayTeam: "TPS Turku",
                    winnerFT: "a",
                    winnerFH: "a",
                    winnerSH: "a",
                    result: "0 - 2",
                    homeScoreFirstHalf: 0,
                    awayScoreFirstHalf: 1,
                    homeScoreSecondHalf: 0,
                    awayScoreSecondHalf: 1,
                    homeScoreFullTime: 0,
                    awayScoreFullTime: 2,
                    goalsFT: 2,
                    goalsHT: 1,
                },
                {
                    gameDate: "2022-05-20",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "JäPS",
                    awayTeam: "FC KTP",
                    winnerFT: "h",
                    winnerFH: "d",
                    winnerSH: "h",
                    result: "2 - 1",
                    homeScoreFirstHalf: 1,
                    awayScoreFirstHalf: 1,
                    homeScoreSecondHalf: 1,
                    awayScoreSecondHalf: 0,
                    homeScoreFullTime: 2,
                    awayScoreFullTime: 1,
                    goalsFT: 3,
                    goalsHT: 2,
                },
                {
                    gameDate: "2022-05-21",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "IF Gnistan",
                    awayTeam: "PIF Parainen",
                    winnerFT: "h",
                    winnerFH: "h",
                    winnerSH: "d",
                    result: "1 - 0",
                    homeScoreFirstHalf: 1,
                    awayScoreFirstHalf: 0,
                    homeScoreSecondHalf: 0,
                    awayScoreSecondHalf: 0,
                    homeScoreFullTime: 1,
                    awayScoreFullTime: 0,
                    goalsFT: 1,
                    goalsHT: 1,
                },
                {
                    gameDate: "2022-05-21",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "EIF Ekenas",
                    awayTeam: "PK-35 Vantaa",
                    winnerFT: "h",
                    winnerFH: "h",
                    winnerSH: "d",
                    result: "2 - 1",
                    homeScoreFirstHalf: 1,
                    awayScoreFirstHalf: 0,
                    homeScoreSecondHalf: 1,
                    awayScoreSecondHalf: 1,
                    homeScoreFullTime: 2,
                    awayScoreFullTime: 1,
                    goalsFT: 3,
                    goalsHT: 1,
                },
                {
                    gameDate: "2022-05-21",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "KPV Kokkola",
                    awayTeam: "SJK Akatemia",
                    winnerFT: "a",
                    winnerFH: "a",
                    winnerSH: "d",
                    result: "0 - 3",
                    homeScoreFirstHalf: 0,
                    awayScoreFirstHalf: 3,
                    homeScoreSecondHalf: 0,
                    awayScoreSecondHalf: 0,
                    homeScoreFullTime: 0,
                    awayScoreFullTime: 3,
                    goalsFT: 3,
                    goalsHT: 3,
                },
                {
                    gameDate: "2022-05-21",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "MP Mikkeli",
                    awayTeam: "FF Jaro",
                    winnerFT: "h",
                    winnerFH: "h",
                    winnerSH: "h",
                    result: "3 - 0",
                    homeScoreFirstHalf: 1,
                    awayScoreFirstHalf: 0,
                    homeScoreSecondHalf: 2,
                    awayScoreSecondHalf: 0,
                    homeScoreFullTime: 3,
                    awayScoreFullTime: 0,
                    goalsFT: 3,
                    goalsHT: 1,
                },
                {
                    gameDate: "2022-05-21",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "TPS Turku",
                    awayTeam: "PEPO",
                    winnerFT: "d",
                    winnerFH: "d",
                    winnerSH: "d",
                    result: "0 - 0",
                    homeScoreFirstHalf: 0,
                    awayScoreFirstHalf: 0,
                    homeScoreSecondHalf: 0,
                    awayScoreSecondHalf: 0,
                    homeScoreFullTime: 0,
                    awayScoreFullTime: 0,
                    goalsFT: 0,
                    goalsHT: 0,
                },
                {
                    gameDate: "2022-05-29",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "SJK Akatemia",
                    awayTeam: "IF Gnistan",
                    winnerFT: "h",
                    winnerFH: "h",
                    winnerSH: "h",
                    result: "4 - 0",
                    homeScoreFirstHalf: 2,
                    awayScoreFirstHalf: 0,
                    homeScoreSecondHalf: 2,
                    awayScoreSecondHalf: 0,
                    homeScoreFullTime: 4,
                    awayScoreFullTime: 0,
                    goalsFT: 4,
                    goalsHT: 2,
                },
                {
                    gameDate: "2022-05-29",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "PK-35 Vantaa",
                    awayTeam: "MP Mikkeli",
                    winnerFT: "h",
                    winnerFH: "h",
                    winnerSH: "h",
                    result: "2 - 0",
                    homeScoreFirstHalf: 1,
                    awayScoreFirstHalf: 0,
                    homeScoreSecondHalf: 1,
                    awayScoreSecondHalf: 0,
                    homeScoreFullTime: 2,
                    awayScoreFullTime: 0,
                    goalsFT: 2,
                    goalsHT: 1,
                },
                {
                    gameDate: "2022-05-29",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "FF Jaro",
                    awayTeam: "TPS Turku",
                    winnerFT: "a",
                    winnerFH: "d",
                    winnerSH: "a",
                    result: "1 - 2",
                    homeScoreFirstHalf: 1,
                    awayScoreFirstHalf: 1,
                    homeScoreSecondHalf: 0,
                    awayScoreSecondHalf: 1,
                    homeScoreFullTime: 1,
                    awayScoreFullTime: 2,
                    goalsFT: 3,
                    goalsHT: 2,
                },
                {
                    gameDate: "2022-05-29",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "PIF Parainen",
                    awayTeam: "JäPS",
                    winnerFT: "a",
                    winnerFH: "d",
                    winnerSH: "a",
                    result: "0 - 1",
                    homeScoreFirstHalf: 0,
                    awayScoreFirstHalf: 0,
                    homeScoreSecondHalf: 0,
                    awayScoreSecondHalf: 1,
                    homeScoreFullTime: 0,
                    awayScoreFullTime: 1,
                    goalsFT: 1,
                    goalsHT: 0,
                },
                {
                    gameDate: "2022-05-30",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "FC KTP",
                    awayTeam: "EIF Ekenas",
                    winnerFT: "d",
                    winnerFH: "d",
                    winnerSH: "d",
                    result: "1 - 1",
                    homeScoreFirstHalf: 0,
                    awayScoreFirstHalf: 0,
                    homeScoreSecondHalf: 1,
                    awayScoreSecondHalf: 1,
                    homeScoreFullTime: 1,
                    awayScoreFullTime: 1,
                    goalsFT: 2,
                    goalsHT: 0,
                },
                {
                    gameDate: "2022-05-30",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "PEPO",
                    awayTeam: "KPV Kokkola",
                    winnerFT: "d",
                    winnerFH: "a",
                    winnerSH: "h",
                    result: "1 - 1",
                    homeScoreFirstHalf: 0,
                    awayScoreFirstHalf: 1,
                    homeScoreSecondHalf: 1,
                    awayScoreSecondHalf: 0,
                    homeScoreFullTime: 1,
                    awayScoreFullTime: 1,
                    goalsFT: 2,
                    goalsHT: 1,
                },
                {
                    gameDate: "2022-06-03",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "JäPS",
                    awayTeam: "SJK Akatemia",
                    winnerFT: "d",
                    winnerFH: "d",
                    winnerSH: "d",
                    result: "1 - 1",
                    homeScoreFirstHalf: 1,
                    awayScoreFirstHalf: 1,
                    homeScoreSecondHalf: 0,
                    awayScoreSecondHalf: 0,
                    homeScoreFullTime: 1,
                    awayScoreFullTime: 1,
                    goalsFT: 2,
                    goalsHT: 2,
                },
                {
                    gameDate: "2022-06-03",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "KPV Kokkola",
                    awayTeam: "FF Jaro",
                    winnerFT: "h",
                    winnerFH: "d",
                    winnerSH: "h",
                    result: "1 - 0",
                    homeScoreFirstHalf: 0,
                    awayScoreFirstHalf: 0,
                    homeScoreSecondHalf: 1,
                    awayScoreSecondHalf: 0,
                    homeScoreFullTime: 1,
                    awayScoreFullTime: 0,
                    goalsFT: 1,
                    goalsHT: 0,
                },
                {
                    gameDate: "2022-06-03",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "FC KTP",
                    awayTeam: "PIF Parainen",
                    winnerFT: "h",
                    winnerFH: "d",
                    winnerSH: "h",
                    result: "3 - 1",
                    homeScoreFirstHalf: 1,
                    awayScoreFirstHalf: 1,
                    homeScoreSecondHalf: 2,
                    awayScoreSecondHalf: 0,
                    homeScoreFullTime: 3,
                    awayScoreFullTime: 1,
                    goalsFT: 4,
                    goalsHT: 2,
                },
                {
                    gameDate: "2022-06-05",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "EIF Ekenas",
                    awayTeam: "MP Mikkeli",
                    winnerFT: "d",
                    winnerFH: "a",
                    winnerSH: "h",
                    result: "2 - 2",
                    homeScoreFirstHalf: 0,
                    awayScoreFirstHalf: 2,
                    homeScoreSecondHalf: 2,
                    awayScoreSecondHalf: 0,
                    homeScoreFullTime: 2,
                    awayScoreFullTime: 2,
                    goalsFT: 4,
                    goalsHT: 2,
                },
                {
                    gameDate: "2022-06-05",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "IF Gnistan",
                    awayTeam: "PEPO",
                    winnerFT: "h",
                    winnerFH: "h",
                    winnerSH: "h",
                    result: "5 - 0",
                    homeScoreFirstHalf: 1,
                    awayScoreFirstHalf: 0,
                    homeScoreSecondHalf: 4,
                    awayScoreSecondHalf: 0,
                    homeScoreFullTime: 5,
                    awayScoreFullTime: 0,
                    goalsFT: 5,
                    goalsHT: 1,
                },
                {
                    gameDate: "2022-06-06",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "TPS Turku",
                    awayTeam: "PK-35 Vantaa",
                    winnerFT: "h",
                    winnerFH: "h",
                    winnerSH: "h",
                    result: "2 - 0",
                    homeScoreFirstHalf: 1,
                    awayScoreFirstHalf: 0,
                    homeScoreSecondHalf: 1,
                    awayScoreSecondHalf: 0,
                    homeScoreFullTime: 2,
                    awayScoreFullTime: 0,
                    goalsFT: 2,
                    goalsHT: 1,
                },
                {
                    gameDate: "2022-06-10",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "PEPO",
                    awayTeam: "JäPS",
                    winnerFT: "a",
                    winnerFH: "h",
                    winnerSH: "a",
                    result: "2 - 4",
                    homeScoreFirstHalf: 2,
                    awayScoreFirstHalf: 0,
                    homeScoreSecondHalf: 0,
                    awayScoreSecondHalf: 4,
                    homeScoreFullTime: 2,
                    awayScoreFullTime: 4,
                    goalsFT: 6,
                    goalsHT: 2,
                },
                {
                    gameDate: "2022-06-10",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "PIF Parainen",
                    awayTeam: "EIF Ekenas",
                    winnerFT: "a",
                    winnerFH: "h",
                    winnerSH: "a",
                    result: "2 - 3",
                    homeScoreFirstHalf: 2,
                    awayScoreFirstHalf: 1,
                    homeScoreSecondHalf: 0,
                    awayScoreSecondHalf: 2,
                    homeScoreFullTime: 2,
                    awayScoreFullTime: 3,
                    goalsFT: 5,
                    goalsHT: 3,
                },
                {
                    gameDate: "2022-06-10",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "MP Mikkeli",
                    awayTeam: "TPS Turku",
                    winnerFT: "d",
                    winnerFH: "a",
                    winnerSH: "h",
                    result: "1 - 1",
                    homeScoreFirstHalf: 0,
                    awayScoreFirstHalf: 1,
                    homeScoreSecondHalf: 1,
                    awayScoreSecondHalf: 0,
                    homeScoreFullTime: 1,
                    awayScoreFullTime: 1,
                    goalsFT: 2,
                    goalsHT: 1,
                },
                {
                    gameDate: "2022-06-11",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "PK-35 Vantaa",
                    awayTeam: "KPV Kokkola",
                    winnerFT: "d",
                    winnerFH: "d",
                    winnerSH: "d",
                    result: "1 - 1",
                    homeScoreFirstHalf: 0,
                    awayScoreFirstHalf: 0,
                    homeScoreSecondHalf: 1,
                    awayScoreSecondHalf: 1,
                    homeScoreFullTime: 1,
                    awayScoreFullTime: 1,
                    goalsFT: 2,
                    goalsHT: 0,
                },
                {
                    gameDate: "2022-06-11",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "SJK Akatemia",
                    awayTeam: "FC KTP",
                    winnerFT: "d",
                    winnerFH: "h",
                    winnerSH: "a",
                    result: "1 - 1",
                    homeScoreFirstHalf: 1,
                    awayScoreFirstHalf: 0,
                    homeScoreSecondHalf: 0,
                    awayScoreSecondHalf: 1,
                    homeScoreFullTime: 1,
                    awayScoreFullTime: 1,
                    goalsFT: 2,
                    goalsHT: 1,
                },
                {
                    gameDate: "2022-06-12",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "FF Jaro",
                    awayTeam: "IF Gnistan",
                    winnerFT: "a",
                    winnerFH: "d",
                    winnerSH: "a",
                    result: "0 - 2",
                    homeScoreFirstHalf: 0,
                    awayScoreFirstHalf: 0,
                    homeScoreSecondHalf: 0,
                    awayScoreSecondHalf: 2,
                    homeScoreFullTime: 0,
                    awayScoreFullTime: 2,
                    goalsFT: 2,
                    goalsHT: 0,
                },
                {
                    gameDate: "2022-06-15",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "FC KTP",
                    awayTeam: "IF Gnistan",
                    winnerFT: "h",
                    winnerFH: "h",
                    winnerSH: "h",
                    result: "4 - 0",
                    homeScoreFirstHalf: 2,
                    awayScoreFirstHalf: 0,
                    homeScoreSecondHalf: 2,
                    awayScoreSecondHalf: 0,
                    homeScoreFullTime: 4,
                    awayScoreFullTime: 0,
                    goalsFT: 4,
                    goalsHT: 2,
                },
                {
                    gameDate: "2022-06-18",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "TPS Turku",
                    awayTeam: "KPV Kokkola",
                    winnerFT: "h",
                    winnerFH: "h",
                    winnerSH: "h",
                    result: "5 - 0",
                    homeScoreFirstHalf: 3,
                    awayScoreFirstHalf: 0,
                    homeScoreSecondHalf: 2,
                    awayScoreSecondHalf: 0,
                    homeScoreFullTime: 5,
                    awayScoreFullTime: 0,
                    goalsFT: 5,
                    goalsHT: 3,
                },
                {
                    gameDate: "2022-06-18",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "EIF Ekenas",
                    awayTeam: "SJK Akatemia",
                    winnerFT: "h",
                    winnerFH: "h",
                    winnerSH: "h",
                    result: "5 - 0",
                    homeScoreFirstHalf: 2,
                    awayScoreFirstHalf: 0,
                    homeScoreSecondHalf: 3,
                    awayScoreSecondHalf: 0,
                    homeScoreFullTime: 5,
                    awayScoreFullTime: 0,
                    goalsFT: 5,
                    goalsHT: 2,
                },
                {
                    gameDate: "2022-06-18",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "PEPO",
                    awayTeam: "PIF Parainen",
                    winnerFT: "h",
                    winnerFH: "h",
                    winnerSH: "d",
                    result: "2 - 1",
                    homeScoreFirstHalf: 2,
                    awayScoreFirstHalf: 1,
                    homeScoreSecondHalf: 0,
                    awayScoreSecondHalf: 0,
                    homeScoreFullTime: 2,
                    awayScoreFullTime: 1,
                    goalsFT: 3,
                    goalsHT: 3,
                },
                {
                    gameDate: "2022-06-18",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "MP Mikkeli",
                    awayTeam: "IF Gnistan",
                    winnerFT: "d",
                    winnerFH: "d",
                    winnerSH: "d",
                    result: "1 - 1",
                    homeScoreFirstHalf: 0,
                    awayScoreFirstHalf: 0,
                    homeScoreSecondHalf: 1,
                    awayScoreSecondHalf: 1,
                    homeScoreFullTime: 1,
                    awayScoreFullTime: 1,
                    goalsFT: 2,
                    goalsHT: 0,
                },
                {
                    gameDate: "2022-06-18",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "FF Jaro",
                    awayTeam: "FC KTP",
                    winnerFT: "d",
                    winnerFH: "h",
                    winnerSH: "a",
                    result: "2 - 2",
                    homeScoreFirstHalf: 1,
                    awayScoreFirstHalf: 0,
                    homeScoreSecondHalf: 1,
                    awayScoreSecondHalf: 2,
                    homeScoreFullTime: 2,
                    awayScoreFullTime: 2,
                    goalsFT: 4,
                    goalsHT: 1,
                },
                {
                    gameDate: "2022-06-18",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "PK-35 Vantaa",
                    awayTeam: "JäPS",
                    winnerFT: "d",
                    winnerFH: "h",
                    winnerSH: "a",
                    result: "2 - 2",
                    homeScoreFirstHalf: 2,
                    awayScoreFirstHalf: 0,
                    homeScoreSecondHalf: 0,
                    awayScoreSecondHalf: 2,
                    homeScoreFullTime: 2,
                    awayScoreFullTime: 2,
                    goalsFT: 4,
                    goalsHT: 2,
                },
                {
                    gameDate: "2022-06-22",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "IF Gnistan",
                    awayTeam: "TPS Turku",
                    winnerFT: "a",
                    winnerFH: "a",
                    winnerSH: "d",
                    result: "0 - 1",
                    homeScoreFirstHalf: 0,
                    awayScoreFirstHalf: 1,
                    homeScoreSecondHalf: 0,
                    awayScoreSecondHalf: 0,
                    homeScoreFullTime: 0,
                    awayScoreFullTime: 1,
                    goalsFT: 1,
                    goalsHT: 1,
                },
                {
                    gameDate: "2022-06-22",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "JäPS",
                    awayTeam: "MP Mikkeli",
                    winnerFT: "a",
                    winnerFH: "a",
                    winnerSH: "d",
                    result: "1 - 4",
                    homeScoreFirstHalf: 0,
                    awayScoreFirstHalf: 3,
                    homeScoreSecondHalf: 1,
                    awayScoreSecondHalf: 1,
                    homeScoreFullTime: 1,
                    awayScoreFullTime: 4,
                    goalsFT: 5,
                    goalsHT: 3,
                },
                {
                    gameDate: "2022-06-22",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "KPV Kokkola",
                    awayTeam: "EIF Ekenas",
                    winnerFT: "d",
                    winnerFH: "a",
                    winnerSH: "h",
                    result: "1 - 1",
                    homeScoreFirstHalf: 0,
                    awayScoreFirstHalf: 1,
                    homeScoreSecondHalf: 1,
                    awayScoreSecondHalf: 0,
                    homeScoreFullTime: 1,
                    awayScoreFullTime: 1,
                    goalsFT: 2,
                    goalsHT: 1,
                },
                {
                    gameDate: "2022-06-22",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "FC KTP",
                    awayTeam: "PK-35 Vantaa",
                    winnerFT: "h",
                    winnerFH: "h",
                    winnerSH: "h",
                    result: "4 - 0",
                    homeScoreFirstHalf: 1,
                    awayScoreFirstHalf: 0,
                    homeScoreSecondHalf: 3,
                    awayScoreSecondHalf: 0,
                    homeScoreFullTime: 4,
                    awayScoreFullTime: 0,
                    goalsFT: 4,
                    goalsHT: 1,
                },
                {
                    gameDate: "2022-06-22",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "PIF Parainen",
                    awayTeam: "FF Jaro",
                    winnerFT: "a",
                    winnerFH: "a",
                    winnerSH: "a",
                    result: "0 - 2",
                    homeScoreFirstHalf: 0,
                    awayScoreFirstHalf: 1,
                    homeScoreSecondHalf: 0,
                    awayScoreSecondHalf: 1,
                    homeScoreFullTime: 0,
                    awayScoreFullTime: 2,
                    goalsFT: 2,
                    goalsHT: 1,
                },
                {
                    gameDate: "2022-06-23",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "SJK Akatemia",
                    awayTeam: "PEPO",
                    winnerFT: "d",
                    winnerFH: "a",
                    winnerSH: "h",
                    result: "2 - 2",
                    homeScoreFirstHalf: 1,
                    awayScoreFirstHalf: 2,
                    homeScoreSecondHalf: 1,
                    awayScoreSecondHalf: 0,
                    homeScoreFullTime: 2,
                    awayScoreFullTime: 2,
                    goalsFT: 4,
                    goalsHT: 3,
                },
                {
                    gameDate: "2022-07-01",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "IF Gnistan",
                    awayTeam: "KPV Kokkola",
                    winnerFT: "a",
                    winnerFH: "a",
                    winnerSH: "d",
                    result: "1 - 2",
                    homeScoreFirstHalf: 0,
                    awayScoreFirstHalf: 1,
                    homeScoreSecondHalf: 1,
                    awayScoreSecondHalf: 1,
                    homeScoreFullTime: 1,
                    awayScoreFullTime: 2,
                    goalsFT: 3,
                    goalsHT: 1,
                },
                {
                    gameDate: "2022-07-01",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "JäPS",
                    awayTeam: "TPS Turku",
                    winnerFT: "a",
                    winnerFH: "d",
                    winnerSH: "a",
                    result: "0 - 1",
                    homeScoreFirstHalf: 0,
                    awayScoreFirstHalf: 0,
                    homeScoreSecondHalf: 0,
                    awayScoreSecondHalf: 1,
                    homeScoreFullTime: 0,
                    awayScoreFullTime: 1,
                    goalsFT: 1,
                    goalsHT: 0,
                },
                {
                    gameDate: "2022-07-01",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "FC KTP",
                    awayTeam: "MP Mikkeli",
                    winnerFT: "h",
                    winnerFH: "h",
                    winnerSH: "h",
                    result: "4 - 1",
                    homeScoreFirstHalf: 2,
                    awayScoreFirstHalf: 1,
                    homeScoreSecondHalf: 2,
                    awayScoreSecondHalf: 0,
                    homeScoreFullTime: 4,
                    awayScoreFullTime: 1,
                    goalsFT: 5,
                    goalsHT: 3,
                },
                {
                    gameDate: "2022-07-02",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "PEPO",
                    awayTeam: "EIF Ekenas",
                    winnerFT: "d",
                    winnerFH: "h",
                    winnerSH: "a",
                    result: "2 - 2",
                    homeScoreFirstHalf: 1,
                    awayScoreFirstHalf: 0,
                    homeScoreSecondHalf: 1,
                    awayScoreSecondHalf: 2,
                    homeScoreFullTime: 2,
                    awayScoreFullTime: 2,
                    goalsFT: 4,
                    goalsHT: 1,
                },
                {
                    gameDate: "2022-07-02",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "PIF Parainen",
                    awayTeam: "PK-35 Vantaa",
                    winnerFT: "h",
                    winnerFH: "h",
                    winnerSH: "d",
                    result: "3 - 2",
                    homeScoreFirstHalf: 1,
                    awayScoreFirstHalf: 0,
                    homeScoreSecondHalf: 2,
                    awayScoreSecondHalf: 2,
                    homeScoreFullTime: 3,
                    awayScoreFullTime: 2,
                    goalsFT: 5,
                    goalsHT: 1,
                },
                {
                    gameDate: "2022-07-02",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "SJK Akatemia",
                    awayTeam: "FF Jaro",
                    winnerFT: "a",
                    winnerFH: "a",
                    winnerSH: "d",
                    result: "1 - 3",
                    homeScoreFirstHalf: 1,
                    awayScoreFirstHalf: 3,
                    homeScoreSecondHalf: 0,
                    awayScoreSecondHalf: 0,
                    homeScoreFullTime: 1,
                    awayScoreFullTime: 3,
                    goalsFT: 4,
                    goalsHT: 4,
                },
                {
                    gameDate: "2022-07-04",
                    country_id: 20,
                    competition_id: 75,
                    season: "2021/2022",
                    homeTeam: "TPS Turku",
                    awayTeam: "FC KTP",
                    winnerFT: "a",
                    winnerFH: "d",
                    winnerSH: "a",
                    result: "1 - 3",
                    homeScoreFirstHalf: 1,
                    awayScoreFirstHalf: 1,
                    homeScoreSecondHalf: 0,
                    awayScoreSecondHalf: 2,
                    homeScoreFullTime: 1,
                    awayScoreFullTime: 3,
                    goalsFT: 4,
                    goalsHT: 2,
                },
            ],
            table: '<div class="allTableContainer"><div class="footballTableFull"><div class="table_under_up_txt" style="text-align: center; margin-left: 20px;"><br/></div><table class="FootballTableFirst"> <tr ><th>&nbsp;</th><th>&nbsp;</th></tr><tr ><th>&nbsp;</th><th>Team</th></tr><tr ><td class="tablePosition" style="background-color: #1b7200 ;">1</td><td class="tableName">TPS Turku</td></tr><tr ><td class="tablePosition" style="background-color: #1b7200 ;">2</td><td class="tableName">FC KTP</td></tr><tr  class="selectTeam" ><td class="tablePosition" style="background-color: #1b7200 ;">3</td><td class="tableName">EIF Ekenas</td></tr><tr  class="selectTeam" ><td class="tablePosition" style="background-color: #1b7200 ;">4</td><td class="tableName">IF Gnistan</td></tr><tr ><td class="tablePosition" style="background-color: #1b7200 ;">5</td><td class="tableName">SJK Akatemia</td></tr><tr ><td class="tablePosition" style="background-color: #1b7200 ;">6</td><td class="tableName">KPV Kokkola</td></tr><tr ><td class="tablePosition" style="background-color: #f2362a ;">7</td><td class="tableName">JäPS</td></tr><tr ><td class="tablePosition" style="background-color: #f2362a ;">8</td><td class="tableName">FF Jaro</td></tr><tr ><td class="tablePosition" style="background-color: #f2362a ;">9</td><td class="tableName">MP Mikkeli</td></tr><tr ><td class="tablePosition" style="background-color: #f2362a ;">10</td><td class="tableName">PEPO</td></tr><tr ><td class="tablePosition" style="background-color: #f2362a ;">11</td><td class="tableName">PIF Parainen</td></tr><tr ><td class="tablePosition" style="background-color: #f2362a ;">12</td><td class="tableName">PK-35 Vantaa</td></tr></table><table class="FootballTableSecond"><tr><th colspan="7">TOTAL</th><th colspan="7">HOME</th><th colspan="7">AWAY</th></tr><tr><th >MP</th><th >W</th><th >D</th><th >L</th><th >F</th><th >A</th><th class="tableStyleBorder">P</th><th >MP</th><th >W</th><th >D</th><th >L</th><th >F</th><th >A</th><th class="tableStyleBorder">PH</th><th >MP</th><th >W</th><th >D</th><th >L</th><th >F</th><th >A</th><th>PA</th></tr><tr ><td>13</td><td >8</td><td >3</td><td >2</td><td >21</td><td>8</td><td class="tableStyleBorder">27</td><td >6</td><td >3</td><td >1</td><td >2</td><td >11</td><td >5</td><td class="tableStyleBorder">10</td><td >7</td><td >5</td><td >2</td><td >0</td><td >10</td><td >3<td><b>17</b></td></tr><tr ><td>12</td><td >7</td><td >4</td><td >1</td><td >27</td><td>10</td><td class="tableStyleBorder">25</td><td >7</td><td >5</td><td >2</td><td >0</td><td >17</td><td >3</td><td class="tableStyleBorder">17</td><td >5</td><td >2</td><td >2</td><td >1</td><td >10</td><td >7<td><b>8</b></td></tr><tr  class="selectTeam" ><td>12</td><td >5</td><td >5</td><td >2</td><td >22</td><td>16</td><td class="tableStyleBorder">20</td><td >6</td><td >4</td><td >1</td><td >1</td><td >14</td><td >8</td><td class="tableStyleBorder">13</td><td >6</td><td >1</td><td >4</td><td >1</td><td >8</td><td >8<td><b>7</b></td></tr><tr  class="selectTeam" ><td>12</td><td >5</td><td >3</td><td >4</td><td >24</td><td>15</td><td class="tableStyleBorder">18</td><td >7</td><td >3</td><td >2</td><td >2</td><td >19</td><td >6</td><td class="tableStyleBorder">11</td><td >5</td><td >2</td><td >1</td><td >2</td><td >5</td><td >9<td><b>7</b></td></tr><tr ><td>11</td><td >4</td><td >4</td><td >3</td><td >19</td><td>16</td><td class="tableStyleBorder">16</td><td >6</td><td >2</td><td >2</td><td >2</td><td >12</td><td >9</td><td class="tableStyleBorder">8</td><td >5</td><td >2</td><td >2</td><td >1</td><td >7</td><td >7<td><b>8</b></td></tr><tr ><td>12</td><td >4</td><td >4</td><td >4</td><td >12</td><td>20</td><td class="tableStyleBorder">16</td><td >6</td><td >2</td><td >1</td><td >3</td><td >6</td><td >11</td><td class="tableStyleBorder">7</td><td >6</td><td >2</td><td >3</td><td >1</td><td >6</td><td >9<td><b>9</b></td></tr><tr ><td>12</td><td >4</td><td >4</td><td >4</td><td >13</td><td>24</td><td class="tableStyleBorder">16</td><td >7</td><td >2</td><td >3</td><td >2</td><td >5</td><td >7</td><td class="tableStyleBorder">9</td><td >5</td><td >2</td><td >1</td><td >2</td><td >8</td><td >17<td><b>7</b></td></tr><tr ><td>11</td><td >4</td><td >2</td><td >5</td><td >16</td><td>13</td><td class="tableStyleBorder">14</td><td >4</td><td >1</td><td >1</td><td >2</td><td >7</td><td >6</td><td class="tableStyleBorder">4</td><td >7</td><td >3</td><td >1</td><td >3</td><td >9</td><td >7<td><b>10</b></td></tr><tr ><td>10</td><td >3</td><td >4</td><td >3</td><td >18</td><td>17</td><td class="tableStyleBorder">13</td><td >4</td><td >1</td><td >3</td><td >0</td><td >6</td><td >3</td><td class="tableStyleBorder">6</td><td >6</td><td >2</td><td >1</td><td >3</td><td >12</td><td >14<td><b>7</b></td></tr><tr ><td>11</td><td >2</td><td >4</td><td >5</td><td >12</td><td>22</td><td class="tableStyleBorder">10</td><td >5</td><td >1</td><td >2</td><td >2</td><td >7</td><td >11</td><td class="tableStyleBorder">5</td><td >6</td><td >1</td><td >2</td><td >3</td><td >5</td><td >11<td><b>5</b></td></tr><tr ><td>12</td><td >2</td><td >1</td><td >9</td><td >14</td><td>23</td><td class="tableStyleBorder">7</td><td >7</td><td >1</td><td >0</td><td >6</td><td >8</td><td >15</td><td class="tableStyleBorder">3</td><td >5</td><td >1</td><td >1</td><td >3</td><td >6</td><td >8<td><b>4</b></td></tr><tr ><td>12</td><td >1</td><td >4</td><td >7</td><td >13</td><td>27</td><td class="tableStyleBorder">7</td><td >5</td><td >1</td><td >3</td><td >1</td><td >8</td><td >7</td><td class="tableStyleBorder">6</td><td >7</td><td >0</td><td >1</td><td >6</td><td >5</td><td >20<td><b>1</b></td></tr></table><div class="legendArrow">&lt;--&nbsp;&nbsp;&nbsp;&nbsp;--&gt;</div><div style="width: 90%; font-size: 12px; padding: 5px;">* P - points, PH - points at home, PA - points away, MP - match played, W - win, D - draw, L - lose, F - goals for, A - goals against </div><div style="width: 100%;"></div><div style="width: 100%;"><div style="width: 100%; padding: 0px 0px 0px 20px;"><p class="legend_colors" style="background-color:#1b7200;"></p><p class="legend_text" >Promotion Group</p></div><div style="width: 100%; padding: 0px 0px 0px 20px;"><p class="legend_colors" style="background-color:#f2362a;"></p><p class="legend_text" >Relegation Group</p></div></div><div class="table_under_up_txt" style="text-align: left; margin-left: 20px;">After 22 games the clubs are separated into Promotion Group and Relegation Group. <br/><br/>Table order in the event of a points tie:<br/>1. total goal difference<br/>2. total goals scored<br/>3. head-to-head score.<br/></div></div></div>',
            H2H: [
                {
                    gameDate: "2022-04-30",
                    country_id: "20",
                    competition_id: "75",
                    season: "2021/2022",
                    homeTeam: "IF Gnistan",
                    awayTeam: "EIF Ekenas",
                    winnerFT: "d",
                    winnerFH: "d",
                    winnerSH: "d",
                    result: "1 - 1",
                    homeScoreFirstHalf: "0",
                    awayScoreFirstHalf: "0",
                    homeScoreSecondHalf: "1",
                    awayScoreSecondHalf: "1",
                    homeScoreFullTime: "1",
                    awayScoreFullTime: "1",
                    goalsFT: "2",
                    goalsHT: "0",
                },
                {
                    gameDate: "2021-10-23",
                    country_id: "20",
                    competition_id: "75",
                    season: "2020/2021",
                    homeTeam: "EIF Ekenas",
                    awayTeam: "IF Gnistan",
                    winnerFT: "h",
                    winnerFH: "h",
                    winnerSH: "h",
                    result: "2 - 0",
                    homeScoreFirstHalf: "1",
                    awayScoreFirstHalf: "0",
                    homeScoreSecondHalf: "1",
                    awayScoreSecondHalf: "0",
                    homeScoreFullTime: "2",
                    awayScoreFullTime: "0",
                    goalsFT: "2",
                    goalsHT: "1",
                },
                {
                    gameDate: "2021-09-10",
                    country_id: "20",
                    competition_id: "75",
                    season: "2020/2021",
                    homeTeam: "IF Gnistan",
                    awayTeam: "EIF Ekenas",
                    winnerFT: "a",
                    winnerFH: "a",
                    winnerSH: "a",
                    result: "0 - 3",
                    homeScoreFirstHalf: "0",
                    awayScoreFirstHalf: "2",
                    homeScoreSecondHalf: "0",
                    awayScoreSecondHalf: "1",
                    homeScoreFullTime: "0",
                    awayScoreFullTime: "3",
                    goalsFT: "3",
                    goalsHT: "2",
                },
                {
                    gameDate: "2021-08-14",
                    country_id: "20",
                    competition_id: "75",
                    season: "2020/2021",
                    homeTeam: "EIF Ekenas",
                    awayTeam: "IF Gnistan",
                    winnerFT: "h",
                    winnerFH: "h",
                    winnerSH: "d",
                    result: "2 - 0",
                    homeScoreFirstHalf: "2",
                    awayScoreFirstHalf: "0",
                    homeScoreSecondHalf: "0",
                    awayScoreSecondHalf: "0",
                    homeScoreFullTime: "2",
                    awayScoreFullTime: "0",
                    goalsFT: "2",
                    goalsHT: "2",
                },
                {
                    gameDate: "2020-10-04",
                    country_id: "20",
                    competition_id: "75",
                    season: "2019/2020",
                    homeTeam: "IF Gnistan",
                    awayTeam: "EIF Ekenas",
                    winnerFT: "d",
                    winnerFH: "h",
                    winnerSH: "a",
                    result: "3 - 3",
                    homeScoreFirstHalf: "1",
                    awayScoreFirstHalf: "0",
                    homeScoreSecondHalf: "2",
                    awayScoreSecondHalf: "3",
                    homeScoreFullTime: "3",
                    awayScoreFullTime: "3",
                    goalsFT: "6",
                    goalsHT: "1",
                },
                {
                    gameDate: "2020-08-10",
                    country_id: "20",
                    competition_id: "75",
                    season: "2019/2020",
                    homeTeam: "EIF Ekenas",
                    awayTeam: "IF Gnistan",
                    winnerFT: "h",
                    winnerFH: "h",
                    winnerSH: "d",
                    result: "2 - 1",
                    homeScoreFirstHalf: "1",
                    awayScoreFirstHalf: "0",
                    homeScoreSecondHalf: "1",
                    awayScoreSecondHalf: "1",
                    homeScoreFullTime: "2",
                    awayScoreFullTime: "1",
                    goalsFT: "3",
                    goalsHT: "1",
                },
                {
                    gameDate: "2017-09-24",
                    country_id: "20",
                    competition_id: "75",
                    season: "2016/2017",
                    homeTeam: "EIF Ekenas",
                    awayTeam: "IF Gnistan",
                    winnerFT: "h",
                    winnerFH: "d",
                    winnerSH: "h",
                    result: "1 - 0",
                    homeScoreFirstHalf: "0",
                    awayScoreFirstHalf: "0",
                    homeScoreSecondHalf: "1",
                    awayScoreSecondHalf: "0",
                    homeScoreFullTime: "1",
                    awayScoreFullTime: "0",
                    goalsFT: "1",
                    goalsHT: "0",
                },
                {
                    gameDate: "2017-07-22",
                    country_id: "20",
                    competition_id: "75",
                    season: "2016/2017",
                    homeTeam: "IF Gnistan",
                    awayTeam: "EIF Ekenas",
                    winnerFT: "a",
                    winnerFH: "d",
                    winnerSH: "a",
                    result: "1 - 2",
                    homeScoreFirstHalf: "1",
                    awayScoreFirstHalf: "1",
                    homeScoreSecondHalf: "0",
                    awayScoreSecondHalf: "1",
                    homeScoreFullTime: "1",
                    awayScoreFullTime: "2",
                    goalsFT: "3",
                    goalsHT: "2",
                },
                {
                    gameDate: "2017-05-28",
                    country_id: "20",
                    competition_id: "75",
                    season: "2016/2017",
                    homeTeam: "IF Gnistan",
                    awayTeam: "EIF Ekenas",
                    winnerFT: "d",
                    winnerFH: "d",
                    winnerSH: "d",
                    result: "1 - 1",
                    homeScoreFirstHalf: "0",
                    awayScoreFirstHalf: "0",
                    homeScoreSecondHalf: "1",
                    awayScoreSecondHalf: "1",
                    homeScoreFullTime: "1",
                    awayScoreFullTime: "1",
                    goalsFT: "2",
                    goalsHT: "0",
                },
            ],
        });
    }
    else {
        return Promise.resolve([]);
    }
};
exports.get = get;
